baseURL = "https://www.your-informani-website.com/"
languageCode = "en-us"
title = "Informani | Expert Financial Forecasting & Power BI Dashboards"

[params]
    description = "Informani transforms complex financial data into clear, actionable forecasts. We combine expert talent with interactive Power BI dashboards to drive confident business decisions."
    author = "Informani Financials"
    logo = "/images/logo.png" # Path relative to the static directory

    [params.address]
        street = "123 Finance Avenue"
        locality = "Amsterdam"
        postalCode = "1012 AB"
        country = "NL"

[menu]
  [[menu.main]]
    name = "The Method"
    url = "/#methode" # ✅ CHANGED
    weight = 10
  [[menu.main]]
    name = "Onboarding"
    url = "/#onboarding" # ✅ CHANGED
    weight = 20
  [[menu.main]]
    name = "Security"
    url = "/#security" # ✅ CHANGED
    weight = 30
  [[menu.main]]
    name = "Solutions"
    url = "/#solutions/" # This link is already correct
    weight = 40
    [menu.main.params]
      has_megamenu = true
  [[menu.main]]
    name = "Why Us"
    url = "/#talent" # ✅ CHANGED
    weight = 50